DROP TABLE IF EXISTS EXCHANGE_RATE;
DROP TABLE IF EXISTS PROVIDER;
DROP TABLE IF EXISTS CURRENCY;

--- PROVIDER ---
CREATE TABLE IF NOT EXISTS PROVIDER
(ID INT AUTO_INCREMENT NOT NULL,
 DESIGNATION VARCHAR(255) NOT NULL,
 BASE_CURRENCY VARCHAR(50) NOT NULL,
 PRIMARY KEY(ID));

--- CURRENCY ---
CREATE TABLE IF NOT EXISTS CURRENCY
(ID INT AUTO_INCREMENT NOT NULL,
 DESIGNATION VARCHAR(255) NOT NULL,
 CODE VARCHAR(50) NOT NULL,
 PRIMARY KEY(ID));

--- EXCHANGE_RATE ---
CREATE TABLE IF NOT EXISTS EXCHANGE_RATE
(ID INT AUTO_INCREMENT NOT NULL,
 CURRENCY_ID VARCHAR(255) NOT NULL,
 PROVIDER_ID NUMERIC(20, 2) NOT NULL,
 PURCHASE NUMERIC(20, 2) NOT NULL,
 SALE NUMERIC(20, 2) NOT NULL,
 CREATED_AT DATE NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCY(ID),
 FOREIGN KEY(PROVIDER_ID) REFERENCES PROVIDER(ID));


--- INSERTS ---

--- PROVIDER ---
INSERT INTO PROVIDER(ID, DESIGNATION, BASE_CURRENCY)
VALUES(1, 'BCI', 'MZN');

--- CURRENCY ---
INSERT INTO CURRENCY(ID, DESIGNATION, CODE)
VALUES(1, 'EURO', 'EUR');
VALUES(2, 'BRITISH POUND', 'GBP');
VALUES(3, 'AMERICAN DOLLAR', 'USD');
VALUES(4, 'RAND', 'ZAR');

--- EXCHANGE_RATE ---
INSERT INTO EXCHANGE_RATE(ID, CURRENCY_ID, PROVIDER_ID, PURCHASE, SALE, CREATED_AT)
VALUES(1, 1, 1, 72.570, 74.510, CURRENT_DATE);
VALUES(2, 2, 1, 84.850, 86.540, CURRENT_DATE);
VALUES(3, 3, 1, 63.200, 64.460, CURRENT_DATE);
VALUES(4, 4, 1, 4.100, 4.180, CURRENT_DATE);

